# Mountain dusk theme for Foot

[main]
term=xterm-256color
font=ZedMono Nerd Font:style=Bold:size=12
line-height=13
pad=5x5
dpi-aware=yes

[scrollback]
lines=10000

[cursor]
style=beam

[colors-dark]
alpha=0.92
background=0a0810
foreground=b8b0ac
selection-foreground=dbd4d0
selection-background=3a2840

regular0=1a1420
regular1=c45068
regular2=5a7848
regular3=a08850
regular4=5a6880
regular5=885078
regular6=508080
regular7=c0b8b4

bright0=6a5058
bright1=d86878
bright2=7a9068
bright3=b8a068
bright4=7888a0
bright5=a06888
bright6=6a9090
bright7=dbd4d0
