[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install --all
'''
merged = '0'

[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'
rev = 'release/rpc'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = "takac/vim-hardtime"
hook_add = '''
" let g:hardtime_default_on = 1
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'romgrk/nvim-treesitter-context'

[[plugins]]
repo = 'elixir-lsp/coc-elixir'
build_on = '''
yarn install && yarn prepack
'''

[[plugins]]
repo = 'lifepillar/vim-gruvbox8'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'

[[plugins]]
repo = 'bluz71/vim-moonfly-colors'

[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'camspiers/animate.vim'

[[plugins]]
repo = 'camspiers/lens.vim'

[[plugins]]
repo = 'hoob3rt/lualine.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'akinsho/nvim-bufferline.lua'

[[plugins]]
repo = 'antoinemadec/coc-fzf'

[[plugins]]
repo = 'digitaltoad/vim-pug'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'leafOfTree/vim-vue-plugin'
hook_add = '''
let g:vim_vue_plugin_config = { 
      \'syntax': {
      \   'template': ['html', 'pug'],
      \   'script': ['javascript', 'typescript'],
      \},
      \'attribute': 1,
      \'keyword': 1,
      \'foldexpr': 1,
      \'debug': 0,
      \}
'''

[[plugins]]
repo = 'pineapplegiant/spaceduck'

[[plugins]]
repo = 'Pocco81/Catppuccino.nvim'
