[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install --all
'''
merged = '0'

[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'
rev = 'release/rpc'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = "takac/vim-hardtime"
hook_add = '''
" let g:hardtime_default_on = 1
'''

[[plugins]]
repo = 'lifepillar/vim-gruvbox8'
hook_add = '''
set background=dark
au MyAutoCmd VimEnter * nested colorscheme gruvbox8_hard
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'elixir-lsp/coc-elixir'
build_on = '''
yarn install && yarn prepack
'''
