[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
depends = 'plenary.nvim'

[[plugins]]
repo = 'camspiers/animate.vim'

[[plugins]]
repo = 'camspiers/lens.vim'

[[plugins]]
repo = 'hoob3rt/lualine.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'akinsho/nvim-bufferline.lua'

[[plugins]]
repo = 'glacambre/firenvim'
hook_post_update = 'call firenvim#install(0)'

[[plugins]]
repo = 'Pocco81/Catppuccino.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = 'plenary.nvim'

[[plugins]]
repo = 'earthly/earthly.vim'
rev = 'main'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'romgrk/nvim-treesitter-context'

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'

[[plugins]]
repo = 'ggandor/lightspeed.nvim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'

[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = ['plenary.nvim', 'nvim-lspconfig']

[[plugins]]
repo = 'ms-jpq/coq_nvim'
rev = 'coq'

[[plugins]]
repo = 'ms-jpq/coq.artifacts'
rev = 'artifacts'

[[plugins]]
repo = 'folke/trouble.nvim'
